name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#   push:
#     tags:
#       - '*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8' 

    - name: Check out code into the module directory
      uses: actions/checkout@v2

    - name: Build
      env:
        WMCORE_ROOT: /home/runner/python
      run: |
        echo "build with"
        python -V
        git clone git@github.com:dmwm/WMCore.git
        pwd
        cd WMCore
        pip install -r requirements.txt
        python setup.py build
